### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ncarboni** [isl/x3ml#158]
Hello,
I am trying to convert a large XML file (1.4gb[1]) to RDF but I am getting the following error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.apache.xerces.xni.XMLString.toString(Unknown Source)
	at org.apache.xerces.parsers.AbstractDOMParser.characters(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at gr.forth.ics.isl.x3ml.X3MLCommandLine.xml(X3MLCommandLine.java:205)
	at gr.forth.ics.isl.x3ml.X3MLCommandLine.xml(X3MLCommandLine.java:215)
	at gr.forth.ics.isl.x3ml.X3MLCommandLine.go(X3MLCommandLine.java:293)
	at gr.forth.ics.isl.x3ml.X3MLCommandLine.main(X3MLCommandLine.java:164)
```

I am using the last 2.1.0 X3ML on a M1 Mac with 16GB of RAM. I tried with 1.9.3 but I have the same problem. 

I can surely split the XML files, but I was wondering if there is a way to assign more memory to x3ml, as currently it does not use more than 4GB, even though more memory is available in the machine.

[1] The same happens with a 800MB XML file

**Comment by ymark** [comment]
This happens because, apart from the XML Input, the corresponding RDF model is created and maintained in memory (and it could be bigger in size than the XML input)

The way X3ML Engine is implemented does not allow partial transformations, so splitting your input resources is the only way, You will find plenty of splitters online.
