### ISSUE TITLE
Exception thrown when using OutputStream instead of PrintWriter

### ISSUE THREAD

**Issue by ymark** [isl/x3ml#77]
When using the X3MLEngineFactory class and in particular the method for exporting the output using an OutputStream (which is not a PrintStream) the following exception is thrown:

```
java.lang.ClassCastException: java.io.BufferedOutputStream cannot be cast to java.io.PrintStream
    at eu.delving.x3ml.X3MLEngineFactory.outputResults(X3MLEngineFactory.java:388)
    at eu.delving.x3ml.X3MLEngineFactory.execute(X3MLEngineFactory.java:334)
    at eu.dnetlib.x3m.X3MLEngineTest.test(X3MLEngineTest.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

This issue has been derived from the PARTHENOS project.

**Comment by ymark** [comment]
The issue has been resolved by updating the corresponding methods and replacing PrintStream with the more generic interface OutputStream.

The functionality will be made available from version 1.7.5
